version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_DB: db
    volumes:
      - "{VOLUME}:/var/lib/postgresql/data"

  admin:
    image: 
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRESQL_PASS: 
      EXPOSED_PORT: 
      EXPOSED_IP: 
